<?php

namespace app\index\controller\common;

use think\Controller;
use think\Db;
use think\session;

/**
 * 用于书写一些通用的方法
 * Class Base
 * @package app\index\controller
 */
class Base extends Controller
{
    /**
     * 可以定义控制器初始化方法_initialize，在该控制器的方法调用之前首先执行
     * 这样就不需要在其他controller在书写执行代码了
     */
//    public function _initialize()
//    {
//        $nowTime = time();
//        $s_time = session('loginTime');
//        parent::_initialize(); // TODO: Change the autogenerated stub
//        if (!session('nickName')) {
//            return $this->error('您没有登陆', url('/index/Index/toLogin'));
//        }
//
//        /**
//         * 判断登录时间
//         */
//        if (($nowTime - $s_time) > 36000) {
//            /*
//             * session('loginTime', null);
//             * 清空session中当前用户的信息
//             * 实现登出
//             */
//            session(null);
//            $this->error('当前用户未登录或登录超时，请重新登录', url('/index/Index/toLogin'));
//        } else {
//            /**
//             * 更新检测时间
//             * 这样可以避免对应的数据进行
//             */
//            session('loginTime', $nowTime);
//        }
//    }

    //获取id对应的用户信息
    public function getUser($id)
    {
        $user = model("common/User")->where("id", $id)->select();
        return $user;
    }

    //获取用户个人最新的五篇文章
    public function getUserArt($id)
    {;
        $article = model("common/Article")->where("customer_id", $id)
            ->where("review_status",'1')->order('issuing_time desc')
            ->limit(5)->select();
        return $article;
    }

    //获取用户收藏的最新五篇文章
    public function getUserCollectArt($id)
    {
        $article = DB::table("collect")->alias('c')
            ->join([['article a', 'c.article_id = a.id']])->where("c.customer_id", $id)
            ->field(['a.id,a.title,a.content,a.issuing_time'])
            ->order('issuing_time desc')->limit(5)
            ->select();
        return $article;
    }
}